### ISSUE TITLE
Error in scraping?

### ISSUE THREAD

**Issue by matifdev** [vashukarn/tiktok-dl#1]
DevTools listening on ws://127.0.0.1:54527/devtools/browser/ee615399-d501-4614-bc2e-dc238910074b
[29096:28356:0624/140712.726:ERROR:device_event_log_impl.cc(208)] [14:07:12.725] Bluetooth: bluetooth_adapter_winrt.cc:1060 Getting Default Adapter failed.
Started Scrolling..
Reached to the end of page
Traceback (most recent call last):
  File "tiktokscraper.py", line 76, in <module>
    main()
  File "tiktokscraper.py", line 50, in main
    element_to_hover = driver.find_element_by_xpath(
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id = "main"]/div[2]/div/div[1]/div/main/div[2]/div[1]/div/div/div/a/div/div/div"}
  (Session info: chrome=83.0.4103.116)

**Comment by rakemen** [comment]
I am getting the exact error now, did you resolve this issue?

**Comment by vashukarn** [comment]
The Xpath for the videos to hover are changes as TikTok likes changing it's UI over and over again. I suggest you check the XPath for the video and replace it with the current XPath in the code on line 50
